## Data loading config

Connection details: 
    SERVER : "aice.database.windows.net"
    DATABASE : "aice"
    UID : "aice_candidate"
    PWD : "@ic3_a3s0c1at3"
    PORT : 1433

Date limits:
    first: "20110101"
    last: "20130101"

Columns to extract:
    - date 
    - hr 
    - weather 
    - temperature 
    - feels_like_temperature 
    - relative_humidity 
    - windspeed 
    - psi 
    - guest_scooter 
    - registered_scooter 

## Preprocessing config

Preprocessing:
    weather_search_strings:
        clear: "\\w*l\\w+r$"
        cloudy: "\\w*l\\w+dy$"
        light snow/rain: "\\w*l\\w+t snow.*"
    weather_ord_encoding:
        clear: 0
        cloudy: 1
        light snow/rain: 2
        heavy snow/rain: 3
    z_threshold: 1.5
    rush_hours: [8, 17, 18]


## Splitting config 

split_config:
    split_random_state: 1
    splits:
        train : 0.7
        test : 0.3

## Machine Learning model/tuning params

ml_config:
    chosen_regressor: "ensemble.RandomForestRegressor"
    regressor_params:
    chosen_scaler: "preprocessing.StandardScaler"
    scaler_params:
        with_mean: true
        with_std: true
    cv_folds: 5
    param_grid:
        n_estimators: [3, 10, 30]
        max_features: [2, 4, 6, 8]

## How verbose the gridsearch output is

verbosity: 1
